CREATE TABLE [dbo].[Artifact] (
    [ArtifactID]         VARCHAR (20)  NOT NULL,
    [Location]           VARCHAR (20)  NULL,
    [BurialNumber]       VARCHAR (50)  NULL,
    [ExcavationYear]     SMALLINT      NULL,
    [Title]              VARCHAR (100) NULL,
    [Description]        VARCHAR (MAX) NULL,
    [Material]           VARCHAR (40)  NULL,
    [Condition]          VARCHAR (20)  NULL,
    [Dimensions]         VARCHAR (20)  NULL,
    [Notes]              VARCHAR (MAX) NULL,
    [ArtifactEra]        VARCHAR (30)  NULL,
    [Provenance]         VARCHAR (30)  NULL,
    [IsSurfaceFind]      BIT           NULL,
    [FindDay]            TINYINT       NULL,
    [FindMonth]          TINYINT       NULL,
    [FindYear]           SMALLINT      NULL,
    [Finder]             VARCHAR (15)  NULL,
    [ExcavatorNum]       VARCHAR (20)  NULL,
    [KomAushimEntryDate] DATE          NULL,
    [StorageSite]        VARCHAR (50)  NULL,
    [LocationAtSite]     VARCHAR (100) NULL,
    [ConservationNotes]  VARCHAR (500) NULL,
    [HasPhotos]          BIT           NULL,
    [PersonID]           INT           NULL,
    CONSTRAINT [PK_Artifact] PRIMARY KEY CLUSTERED ([ArtifactID] ASC),
    CONSTRAINT [FK_Artifact_Burial] FOREIGN KEY ([Location], [ExcavationYear], [BurialNumber]) REFERENCES [dbo].[Burial] ([Location], [ExcavationYear], [BurialNumber]),
    CONSTRAINT [FK_Artifact_Location] FOREIGN KEY ([Location]) REFERENCES [dbo].[Location] ([Location]),
    CONSTRAINT [FK_Artifact_Person] FOREIGN KEY ([PersonID]) REFERENCES [dbo].[Person] ([PersonID])
);

